[package]
name = "omoide-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
omoide-crypto = { path = "../omoide-crypto" }
omoide-format = { path = "../omoide-format" }
serde         = { workspace = true }
ciborium      = { workspace = true }
thiserror     = { workspace = true }
zeroize       = { workspace = true }
secrecy       = { workspace = true }
libc          = { workspace = true }
uuid          = { workspace = true }
omoide-env = { version = "0.1.0", path = "../omoide-env" }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true }

[dev-dependencies]
tempfile = "3.8"

[lib]
name = "omoide_core"
path = "src/lib.rs"

[[bin]]
name = "omoide"
path = "src/main.rs"
