[package]
name = "omoide-crypto"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
argon2.workspace = true
hkdf.workspace = true
secrecy.workspace = true
sha2.workspace = true
thiserror.workspace = true
zeroize   = { workspace = true }
serde = { workspace = true }
omoide-env = { path = "../omoide-env", version = "0.1" }