use omoide_crypto::kdf::KdfParams;
use serde::{Deserialize, Serialize};
use zeroize::ZeroizeOnDrop;
use omoide_env::*;

/// Plaintext vault header — stored unencrypted at the start of vault.db.
///
/// Contains everything needed to re-derive the MasterKey from the master
/// password. Must be read before any decryption can occur.
///
/// ### Security
/// 
/// This struct is intentionally plaintext. An attacker with the vault file
/// can read these fields — that is acceptable because:
/// - `kdf_params` and `salt` are needed to derive the key, not to bypass it
/// - `header_aad` is random and useless without the MasterKey
/// - None of these fields reduce the security of the encrypted entries
#[derive(Debug, Serialize, Deserialize)]
pub struct VaultHeader {
    /// Argon2id parameters — frozen at vault creation time.
    /// Changing these requires a vault migration tool.
    pub kdf_params: KdfParams,

    /// 32 random bytes — KDF salt, unique per vault, never reused.
    /// Generated by OsRng at vault creation.
    pub salt: [u8; KDF_SALT_SIZE],

    /// 32 random bytes — bound into every AEAD tag as Additional
    /// Authenticated Data. Prevents transplanting EncryptedEntry records
    /// from one vault into another vault.
    pub header_aad: [u8; HEADER_AAD_SIZE],
}

/// A single encrypted vault entry as stored in vault.db.
///
/// The plaintext is a CBOR-serialized `Entry` struct, encrypted with
/// AES-256-GCM using a per-entry key derived via HKDF from the MasterKey.
///
/// ### Nonce uniqueness
/// A fresh 12-byte nonce is generated from OsRng for every seal operation.
/// Nonce reuse under the same key is catastrophic for AES-GCM — the fresh
/// nonce guarantee must never be violated.
#[derive(Debug, Serialize, Deserialize)]
pub struct EncryptedEntry {
    /// UUID identifying this entry.
    /// Also used as the HKDF salt when deriving this entry's encryption key.
    pub id: [u8; ENTRY_ID_SIZE],

    /// AES-256-GCM nonce — fresh OsRng per seal operation.
    pub nonce: [u8; AES_NONCE_SIZE],

    /// AES-256-GCM ciphertext with Poly1305 tag appended.
    /// Decrypts to CBOR-serialized plaintext Entry bytes.
    pub ciphertext: Vec<u8>,
}

/// The complete in-memory representation of vault.db.
///
/// Loaded entirely into memory on vault unlock, written atomically on seal.
#[derive(Debug, Serialize, Deserialize)]
pub struct VaultFile {
    pub header:  VaultHeader,
    pub entries: Vec<EncryptedEntry>,
}

/// Plaintext entry — exists only in memory, never written to disk unencrypted.
///
/// Serialized to CBOR bytes, then encrypted into EncryptedEntry.ciphertext.
#[derive(Debug, Serialize, Deserialize, ZeroizeOnDrop)]
pub struct Entry {
    pub title:    String,
    pub username: String,
    pub password: String,
    pub url:      String,
    pub notes:    String,
    pub created:  u64,  // Unix timestamp
    pub updated:  u64,  // Unix timestamp
}